"""Generator for the Access compatibility runtime (plan §8, §22).

Emits the `access/` Java package so converted VBA maps onto a small stable
API instead of every generator re-implementing Access semantics:

    Nz()             -> AccessRuntime.nz()
    IsNull()         -> AccessRuntime.isNull()
    IIf()            -> AccessRuntime.iif()
    CDbl/CStr/...    -> AccessRuntime.cDbl()/cStr()/...
    Format() dates   -> AccessDateFunctions.format()
    DLookup/DCount   -> AccessQueryFunctions (JdbcTemplate-backed)

Only the classes actually needed by the conversion are emitted.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class RuntimeUsage:
    """Track which compatibility functions converted code needs."""
    nz: bool = False
    is_null: bool = False
    iif: bool = False
    conversion: bool = False          # CDbl / CInt / CLng / CStr / CBool
    date_functions: bool = False
    string_functions: bool = False
    query_functions: bool = False     # dLookup / dCount / dMax
    error_handling: bool = False

    def any(self) -> bool:
        return any([self.nz, self.is_null, self.iif, self.conversion,
                    self.date_functions, self.string_functions,
                    self.query_functions])


_ACCESS_RUNTIME = '''package {package}.access;

/**
 * Access expression runtime — semantic equivalents of pervasive VBA helpers.
 *
 * Null handling follows VBA rules: Nz(Nothing, x) = x; comparisons against
 * null return null rather than false. Generated code must route these calls
 * here rather than inlining equivalents so edge cases stay fixed in one place.
 *
 * ACCESS-RUNTIME: generated by the converter; manual edits will be overwritten.
 */
public final class AccessRuntime {{

    private AccessRuntime() {{}}

    /** VBA Nz(): Nothing -> replacement value. */
    public static Object nz(Object value, Object replacement) {{
        return value == null ? replacement : value;
    }}

    public static Object nz(Object value) {{
        return nz(value, "");
    }}

    /** VBA IsNull(). */
    public static boolean isNull(Object value) {{
        return value == null;
    }}

    /** VBA IIf(): both branches are evaluated, mirroring Access eagerness. */
    public static Object iif(boolean condition, Object thenValue, Object elseValue) {{
        return condition ? thenValue : elseValue;
    }}

    /**
     * Variant equality with Access semantics.  Converted state arrays use
     * null for VBA's auto-initialized Empty, so null compares equal to ""
     * / 0 / false (Empty coercions) but never to a real value.
     */
    public static boolean eq(Object left, Object right) {{
        if (left == null || right == null) {{
            Object other = left == null ? right : left;
            if (other instanceof String) return ((String) other).isEmpty();
            if (other instanceof Number) return cDbl(other) == 0d;
            if (other instanceof Boolean) return !((Boolean) other);
            return false;
        }}
        java.math.BigDecimal a = toBigDecimal(left);
        java.math.BigDecimal b = toBigDecimal(right);
        if (a != null && b != null && !isStringLike(left) && !isStringLike(right)) {{
            return a.compareTo(b) == 0;
        }}
        if (left instanceof Boolean || right instanceof Boolean) {{
            return cBool(left) == cBool(right);
        }}
        return String.valueOf(left).equals(String.valueOf(right));
    }}

    private static boolean isStringLike(Object o) {{
        return o instanceof String;
    }}

    /** Iterates collections / arrays / Iterables for For Each conversion. */
    @SuppressWarnings("rawtypes")
    public static Iterable<?> iterate(Object value) {{
        if (value == null) return java.util.List.of();
        if (value instanceof Iterable) return (Iterable<?>) value;
        throw new IllegalArgumentException(
                "For Each target is not iterable after conversion: "
                        + value.getClass().getName());
    }}


    // -------------------------------------------------- variant arithmetic

    /** VBA Variant '+': numeric addition (strings would be a type mismatch). */
    public static double add(Object a, Object b) {{
        return cDbl(a) + cDbl(b);
    }}

    public static double sub(Object a, Object b) {{
        return cDbl(a) - cDbl(b);
    }}

    public static double mul(Object a, Object b) {{
        return cDbl(a) * cDbl(b);
    }}

    /** VBA '/': floating division; divide-by-zero raises like Access. */
    public static double div(Object a, Object b) {{
        double d = cDbl(b);
        if (d == 0d) {{
            throw new ArithmeticException("Division by zero");
        }}
        return cDbl(a) / d;
    }}

    /** VBA '&': always string concatenation with implicit cStr(). */
    public static String concat(Object a, Object b) {{
        return cStr(a) + cStr(b);
    }}

    /** VBA Mod: operands round to integers before the remainder. */
    public static long mod(Object a, Object b) {{
        long x = Math.round(cDbl(a));
        long y = Math.round(cDbl(b));
        if (y == 0L) {{
            throw new ArithmeticException("Division by zero (Mod)");
        }}
        return x % y;
    }}

    /** VBA '\\': integer division with operand rounding. */
    public static long idiv(Object a, Object b) {{
        long x = Math.round(cDbl(a));
        long y = Math.round(cDbl(b));
        if (y == 0L) {{
            throw new ArithmeticException("Division by zero (\\)");
        }}
        return x / y;
    }}

    /** VBA Int(): floor toward negative infinity. */
    public static long intFloor(Object value) {{
        return (long) Math.floor(cDbl(value));
    }}

    /** VBA Fix(): truncate toward zero. */
    public static long fix(Object value) {{
        return (long) cDbl(value);
    }}

    /** VBA IsNumeric(). */
    public static boolean isNumeric(Object value) {{
        if (value == null) return false;
        if (value instanceof Number) return true;
        String s = value.toString().trim();
        if (s.isEmpty()) return false;
        try {{
            new java.math.BigDecimal(s);
            return true;
        }} catch (NumberFormatException e) {{
            return false;
        }}
    }}

    /** VBA Val(): numeric value of leading numeric text. */
    public static double val(Object value) {{
        if (value == null) return 0d;
        if (value instanceof Number) return ((Number) value).doubleValue();
        String s = value.toString().stripLeading();
        java.util.regex.Matcher m = java.util.regex.Pattern
                .compile("[-+]?(\\d+\\.?\\d*|\\.\\d+)([eE][-+]?\\d+)?")
                .matcher(s);
        if (m.find() && m.start() == 0) {{
            try {{
                return Double.parseDouble(m.group());
            }} catch (NumberFormatException ignored) {{
                return 0d;
            }}
        }}
        return 0d;
    }}

    /**
     * Placeholder for calls the converter could not resolve. Keeps the
     * generated project compiling while marking the procedure MANUAL_REVIEW
     * in the migration report (plan §28).
     */
    public static Object unsupported(String what, Object... args) {{
        System.err.println("[ACCESS-MIGRATION] unresolved call: " + what);
        return null;
    }}

    // -------------------------------------------------- scalar comparisons

    /**
     * Variant comparison for sorted-detection logic: negative when left
     * sorts before right. Numbers compare numerically regardless of storage
     * type; everything else compares as strings.
     */
    @SuppressWarnings({{"unchecked", "rawtypes"}})
    public static int compare(Object left, Object right) {{
        if (left == null && right == null) return 0;
        if (left == null) return -1;
        if (right == null) return 1;
        Comparable a = asComparable(left);
        Comparable b = asComparable(right);
        if (a.getClass().equals(b.getClass()) || (isNumber(a) && isNumber(b))) {{
            java.math.BigDecimal da = toBigDecimal(a);
            java.math.BigDecimal db = toBigDecimal(b);
            if (da != null && db != null) {{
                return da.compareTo(db);
            }}
        }}
        return String.valueOf(left).compareTo(String.valueOf(right));
    }}

    private static boolean isNumber(Object o) {{
        return o instanceof Number;
    }}

    private static Comparable asComparable(Object o) {{
        return (Comparable) o;
    }}

    private static java.math.BigDecimal toBigDecimal(Object o) {{
        try {{
            if (o instanceof Number) {{
                return new java.math.BigDecimal(o.toString());
            }}
            return new java.math.BigDecimal(o.toString());
        }} catch (NumberFormatException e) {{
            return null;
        }}
    }}

    // -------------------------------------------------- conversions

    public static double cDbl(Object value) {{
        if (value == null) return 0d;
        if (value instanceof Number) return ((Number) value).doubleValue();
        if (value instanceof Boolean) return ((Boolean) value) ? 1d : 0d;
        String s = value.toString().trim();
        if (s.isEmpty()) return 0d;
        try {{
            return Double.parseDouble(s);
        }} catch (NumberFormatException e) {{
            throw new IllegalArgumentException("CType conversion failed for: " + s);
        }}
    }}

    public static long cLng(Object value) {{ return (long) cDbl(value); }}
    public static int cInt(Object value) {{ return (int) Math.round(cDbl(value)); }}

    public static String cStr(Object value) {{
        if (value == null) return "";
        if (value instanceof Boolean) return ((Boolean) value) ? "True" : "False";
        return value.toString();
    }}

    public static boolean cBool(Object value) {{
        if (value == null) return false;
        if (value instanceof Boolean) return (Boolean) value;
        if (value instanceof Number) return ((Number) value).doubleValue() != 0;
        String s = value.toString().trim();
        return "true".equalsIgnoreCase(s) || "1".equals(s);
    }}

    public static java.time.LocalDateTime cDate(Object value) {{
        if (value instanceof java.time.LocalDateTime) return (java.time.LocalDateTime) value;
        if (value instanceof java.time.LocalDate) return ((java.time.LocalDate) value).atStartOfDay();
        if (value == null) return null;
        String s = value.toString().trim();
        java.time.LocalDateTime dt = AccessDateFunctions.parseDateTime(s);
        if (dt == null) {{
            throw new IllegalArgumentException("CDate failed for: " + s);
        }}
        return dt;
    }}
}}
'''

_ACCESS_DATE = '''package {package}.access;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * VBA date-function semantics on JVM types.
 *
 * ACCESS-RUNTIME: generated by the converter; manual edits will be overwritten.
 */
public final class AccessDateFunctions {{

    private AccessDateFunctions() {{}}

    public static LocalDateTime now() {{ return LocalDateTime.now(); }}

    public static LocalDate date() {{ return LocalDate.now(); }}

    public static int year(LocalDateTime dt) {{ return dt.getYear(); }}
    public static int month(LocalDateTime dt) {{ return dt.getMonthValue(); }}
    public static int day(LocalDateTime dt) {{ return dt.getDayOfMonth(); }}

    public static LocalDateTime dateAdd(String interval, double amount, LocalDateTime dt) {{
        if (dt == null) return null;
        long n = (long) amount;
        switch (interval.toLowerCase()) {{
            case "yyyy": case "year": return dt.plusYears(n);
            case "q": case "quarter": return dt.plusMonths(n * 3L);
            case "m": case "month": return dt.plusMonths(n);
            case "d": case "day": case "y": case "w": case "ww":
                return dt.plusDays(interval.equalsIgnoreCase("ww") ? n * 7L : n);
            case "h": return dt.plusHours(n);
            case "n": return dt.plusMinutes(n);
            case "s": return dt.plusSeconds(n);
            default: throw new IllegalArgumentException("bad DateAdd interval: " + interval);
        }}
    }}

    public static long dateDiff(String interval, LocalDateTime start, LocalDateTime end) {{
        if (start == null || end == null) return 0L;
        switch (interval.toLowerCase()) {{
            case "yyyy": case "year": return java.time.temporal.ChronoUnit.YEARS.between(start, end);
            case "q": case "quarter": return java.time.temporal.ChronoUnit.MONTHS.between(start, end) / 3;
            case "m": case "month": return java.time.temporal.ChronoUnit.MONTHS.between(start, end);
            case "d": case "y": return java.time.temporal.ChronoUnit.DAYS.between(start.toLocalDate(), end.toLocalDate());
            case "w": case "ww": return java.time.temporal.ChronoUnit.WEEKS.between(start.toLocalDate(), end.toLocalDate());
            case "h": return java.time.temporal.ChronoUnit.HOURS.between(start, end);
            case "n": return java.time.temporal.ChronoUnit.MINUTES.between(start, end);
            case "s": return java.time.temporal.ChronoUnit.SECONDS.between(start, end);
            default: throw new IllegalArgumentException("bad DateDiff interval: " + interval);
        }}
    }}

    /** VBA DatePart() with firstday=1 (Sunday), firstweek=0 (system default). */
    public static int datePart(String interval, LocalDateTime dt) {{
        if (dt == null) return 0;
        switch (interval.toLowerCase()) {{
            case "yyyy": case "year": return dt.getYear();
            case "q": return ((dt.getMonthValue() - 1) / 3) + 1;
            case "m": return dt.getMonthValue();
            case "d": return dt.getDayOfMonth();
            case "y": return dt.getDayOfYear();
            case "w": return dt.getDayOfWeek().getValue() % 7;      // Sunday=1..Saturday=7
            case "ww": return (dt.getDayOfYear() + 6) / 7;
            case "h": return dt.getHour();
            case "n": return dt.getMinute();
            case "s": return dt.getSecond();
            default: throw new IllegalArgumentException("bad DatePart interval: " + interval);
        }}
    }}

    private static final DateTimeFormatter[] PARSE_FORMATS = {{
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"),
        DateTimeFormatter.ofPattern("yyyy-MM-dd"),
        DateTimeFormatter.ofPattern("MM/dd/yyyy"),
        DateTimeFormatter.ofPattern("M/d/yyyy"),
    }};

    public static LocalDateTime parseDateTime(String s) {{
        for (DateTimeFormatter f : PARSE_FORMATS) {{
            try {{
                if (f.toString().length() > 10 && !f.equals(PARSE_FORMATS[1])
                        && !f.equals(PARSE_FORMATS[2]) && !f.equals(PARSE_FORMATS[3])) {{
                    return LocalDateTime.parse(s.trim(), f);
                }}
                return LocalDate.parse(s.trim(), f).atStartOfDay();
            }} catch (Exception ignored) {{
                // try next format
            }}
        }}
        return null;
    }}
}}
'''

_ACCESS_QUERY = '''package {package}.access;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * Domain-aggregate access functions (VBA DLookup/DCount/DMax/DMin).
 *
 * Runs through JdbcTemplate against the migrated PostgreSQL schema.
 *
 * ACCESS-RUNTIME: generated by the converter; manual edits will be overwritten.
 */
@Component
public class AccessQueryFunctions {{

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private String ident(String column) {{
        return '"' + column.replace("\\"", "") + '"';
    }}

    public Object dLookup(String expr, String domain, String criteria) {{
        String sql = "SELECT " + expr + " FROM " + domain
                + (criteria == null || criteria.isBlank() ? "" : " WHERE " + criteria);
        List<Object> rows = jdbcTemplate.queryForList(sql, Object.class);
        return rows.isEmpty() ? null : rows.get(0);
    }}

    public long dCount(String expr, String domain, String criteria) {{
        String sql = "SELECT COUNT(" + ("*".equals(expr) ? "*" : ident(expr)) + ") FROM " + domain
                + (criteria == null || criteria.isBlank() ? "" : " WHERE " + criteria);
        Long v = jdbcTemplate.queryForObject(sql, Long.class);
        return v == null ? 0L : v;
    }}

    public Object dMax(String expr, String domain, String criteria) {{
        return aggregate("MAX", expr, domain, criteria);
    }}

    public Object dMin(String expr, String domain, String criteria) {{
        return aggregate("MIN", expr, domain, criteria);
    }}

    private Object aggregate(String fn, String expr, String domain, String criteria) {{
        String sql = "SELECT " + fn + "(" + ident(expr) + ") FROM " + domain
                + (criteria == null || criteria.isBlank() ? "" : " WHERE " + criteria);
        return jdbcTemplate.queryForObject(sql, Object.class);
    }}
}}
'''

_ACCESS_STRINGS = '''package {package}.access;

/**
 * VBA string-function helpers that have no direct one-call JDK equivalent.
 *
 * ACCESS-RUNTIME: generated by the converter; manual edits will be overwritten.
 */
public final class AccessStrings {{

    private AccessStrings() {{}}

    public static String right(String s, int count) {{
        if (s == null) return "";
        int n = Math.max(0, Math.min(count, s.length()));
        return s.substring(s.length() - n);
    }}
}}
'''

_VBA_GOTO_SIGNAL = '''package {package}.access;

/**
 * Internal control-flow signal used by generated procedures to implement
 * VBA GoTo jumps across structured-Java blocks.  Not part of any API.
 *
 * ACCESS-RUNTIME: generated by the converter; manual edits will be overwritten.
 */
@SuppressWarnings("serial")
public final class VbaGotoSignal extends RuntimeException {{

    public final String label;

    public VbaGotoSignal(String label) {{
        super(null, null, false, false);
        this.label = label;
    }}
}}
'''

_ACCESS_ERROR = '''package {package}.access;

/**
 * Maps VBA Err object behaviour onto thrown exceptions.
 *
 * ACCESS-RUNTIME: generated by the converter; manual edits will be overwritten.
 */
public final class AccessError {{

    private AccessError() {{}}

    public static void log(String where, RuntimeException e) {{
        System.err.println("[ACCESS-ERR] " + where + ": "
                + e.getMessage());
    }}

    public static int number(RuntimeException e) {{
        return e.hashCode();   // no direct Err.Number equivalent; see report
    }}
}}
'''


def emit_runtime_files(base_package: str, usage: RuntimeUsage) -> dict[str, str]:
    """Return access/*.java sources required by current usage."""
    pkg = base_package
    files: dict[str, str] = {}
    if usage.any():
        files["AccessRuntime.java"] = _ACCESS_RUNTIME.format(package=pkg)
        files["AccessDateFunctions.java"] = _ACCESS_DATE.format(package=pkg)
        # goto bridge + string helpers accompany every runtime package
        files["VbaGotoSignal.java"] = _VBA_GOTO_SIGNAL.format(package=pkg)
        files["AccessStrings.java"] = _ACCESS_STRINGS.format(package=pkg)
    if usage.error_handling:
        files["AccessError.java"] = _ACCESS_ERROR.format(package=pkg)
    if usage.query_functions:
        files["AccessQueryFunctions.java"] = _ACCESS_QUERY.format(package=pkg)
    return files
