"""Spring Boot report endpoint generator (spec sections 20, 43, 45).

Emits, for an application that has at least one convertible report:

    report/ReportDefinition.java   immutable descriptor (record)
    report/ReportRegistry.java     the generated catalogue: SQL + fields + params
    report/ReportService.java      executes via NamedParameterJdbcTemplate
    report/ReportRow.java          one result row, order preserved
    report/ReportData.java         rows + resolved definition
    report/CsvReportWriter.java    RFC 4180 CSV
    report/PdfReportWriter.java    OpenPDF tabular PDF with groups + totals
    report/ReportController.java   JSON / CSV / PDF endpoints

Design constraints this file honours:

  * Report SQL is generated, not user-supplied, and parameters are always
    bound through NamedParameterJdbcTemplate — never string-concatenated.
    A generated app must not ship a SQL-injection hole.
  * Only reports the converter could fully translate are registered. An
    UNSUPPORTED report is emitted as a comment in the registry, so the gap is
    visible in the generated source instead of silently missing.
  * The OpenPDF dependency is only added to pom.xml when a report exists,
    per spec section 29: "Every generated dependency should have an
    originating Access requirement."
"""
from __future__ import annotations

from typing import Iterable

from ..ir.models import SupportStatus
from .model import ReportDefinition, ReportField, ReportFieldType

__all__ = [
    "PDF_DEPENDENCY",
    "SpringReportGenerator",
    "generate_report_sources",
]


# Verified present on Maven Central 2026-08-24 (see technology-versions.json).
PDF_DEPENDENCY = {
    "groupId": "com.github.librepdf",
    "artifactId": "openpdf",
    "version": "3.0.5",
}

_JAVA_TYPE_DEFAULTS = {
    "Long": "Long",
    "Integer": "Integer",
    "Double": "Double",
    "Float": "Float",
    "Boolean": "Boolean",
    "String": "String",
}


def _q(text: str) -> str:
    """Escape a Python string for embedding in a Java string literal."""
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "")
        .replace("\t", "\\t")
    )


class SpringReportGenerator:
    """Generates the report package for the Spring Boot backend."""

    def __init__(
        self,
        definitions: Iterable[ReportDefinition],
        *,
        base_package: str = "com.generated.app",
        report_strategy: str = "pdf",
    ):
        self.all_definitions = list(definitions)
        self.definitions = [d for d in self.all_definitions if d.generatable]
        self.skipped = [d for d in self.all_definitions if not d.generatable]
        self.base_package = base_package
        self.package = f"{base_package}.report"
        strategy = (report_strategy or "pdf").strip().lower()
        # CSV is always available (no dependency); PDF is opt-out.
        self.pdf_enabled = strategy in ("pdf", "both", "all", "pdf+csv", "csv+pdf")

    # ------------------------------------------------------------ public

    @property
    def needs_pdf_dependency(self) -> bool:
        """True when pom.xml must gain the PDF library."""
        return bool(self.definitions) and self.pdf_enabled

    def generate(self) -> dict[str, str]:
        """Return {relative java path -> source}. Empty when no reports exist."""
        if not self.all_definitions:
            return {}

        files = {
            "ReportDefinition.java": self._definition_class(),
            "ReportRegistry.java": self._registry_class(),
            "ReportRow.java": self._row_class(),
            "ReportData.java": self._data_class(),
            "ReportService.java": self._service_class(),
            "CsvReportWriter.java": self._csv_writer(),
            "ReportController.java": self._controller_class(),
        }
        if self.needs_pdf_dependency:
            files["PdfReportWriter.java"] = self._pdf_writer()
        return files

    # ------------------------------------------------------------ classes

    def _definition_class(self) -> str:
        return f"""package {self.package};

import java.util.List;
import java.util.Map;

/**
 * Descriptor for one converted Access report.
 *
 * <p>Instances are created only by {{@link ReportRegistry}} at class-init time;
 * the SQL is generated by the converter and is never assembled from request
 * input. Parameters are bound by name at execution time.
 */
public record ReportDefinition(
        String name,
        String title,
        String endpoint,
        String sql,
        List<Column> columns,
        List<Group> groups,
        List<Total> totals,
        List<Parameter> parameters,
        String supportStatus,
        List<String> notes) {{

    /** A rendered column. {{@code key}} is the result-set label. */
    public record Column(String key, String label, String type, String align) {{
        public boolean numeric() {{
            return "NUMBER".equals(type) || "CURRENCY".equals(type);
        }}
    }}

    /** A grouping level; rows break whenever {{@code key}}'s value changes. */
    public record Group(String key, String label, String direction) {{}}

    /** An aggregate shown in group and report footers. */
    public record Total(String key, String function, String label) {{}}

    /** A named bind parameter required by the report SQL. */
    public record Parameter(String name, String accessName, String javaType, boolean required) {{}}

    /** Column keys in render order. */
    public List<String> columnKeys() {{
        return columns.stream().map(Column::key).toList();
    }}

    /** Look up a column by its result-set key. */
    public Column column(String key) {{
        return columns.stream()
                .filter(c -> c.key().equals(key))
                .findFirst()
                .orElse(null);
    }}

    /**
     * Resolve raw request parameters into typed bind values.
     *
     * @throws IllegalArgumentException if a required parameter is missing or
     *         cannot be converted to its declared type
     */
    public Map<String, Object> bind(Map<String, String> request) {{
        Map<String, Object> bound = new java.util.LinkedHashMap<>();
        for (Parameter p : parameters) {{
            String raw = request == null ? null : request.get(p.name());
            if (raw == null || raw.isBlank()) {{
                if (p.required()) {{
                    throw new IllegalArgumentException(
                            "Report '" + name + "' requires parameter '" + p.name()
                                    + "' (Access: " + p.accessName() + ")");
                }}
                bound.put(p.name(), null);
                continue;
            }}
            bound.put(p.name(), convert(p, raw.trim()));
        }}
        return bound;
    }}

    private Object convert(Parameter p, String raw) {{
        try {{
            return switch (p.javaType()) {{
                case "Long" -> Long.valueOf(raw);
                case "Integer" -> Integer.valueOf(raw);
                case "Double" -> Double.valueOf(raw);
                case "Float" -> Float.valueOf(raw);
                case "Boolean" -> parseBoolean(raw);
                case "java.math.BigDecimal" -> new java.math.BigDecimal(raw);
                case "java.time.LocalDateTime" -> parseTimestamp(raw);
                default -> raw;
            }};
        }} catch (RuntimeException ex) {{
            throw new IllegalArgumentException(
                    "Parameter '" + p.name() + "' expected " + p.javaType()
                            + " but got '" + raw + "'", ex);
        }}
    }}

    private static Boolean parseBoolean(String raw) {{
        return switch (raw.toLowerCase()) {{
            case "true", "yes", "y", "1", "-1", "on" -> Boolean.TRUE;
            case "false", "no", "n", "0", "off" -> Boolean.FALSE;
            default -> throw new IllegalArgumentException("not a boolean: " + raw);
        }};
    }}

    private static java.time.LocalDateTime parseTimestamp(String raw) {{
        // Accept both a plain date and a full timestamp.
        if (raw.length() <= 10) {{
            return java.time.LocalDate.parse(raw).atStartOfDay();
        }}
        return java.time.LocalDateTime.parse(raw.replace(' ', 'T'));
    }}
}}
"""

    def _registry_class(self) -> str:
        entries = "\n".join(self._registry_entry(d) for d in self.definitions)

        skipped_comment = ""
        if self.skipped:
            lines = [
                "",
                "    /*",
                "     * Reports the converter could NOT translate. They are listed here",
                "     * so the gap is visible in the generated source (spec section 61:",
                "     * never silently fake behavior). See migration-report/reports.json.",
                "     *",
            ]
            for d in self.skipped:
                lines.append(f"     *   {d.name} ({d.source or 'no record source'})")
                for blocker in d.blockers:
                    lines.append(f"     *       - {blocker}")
            lines.append("     */")
            skipped_comment = "\n".join(lines)

        count = len(self.definitions)
        return f"""package {self.package};

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Generated catalogue of converted Access reports ({count} registered).
 *
 * <p>Every SQL string here was produced by the converter's deterministic
 * Access-SQL translator. Request values reach the database only as bound
 * parameters.
 */
public final class ReportRegistry {{

    private static final Map<String, ReportDefinition> BY_ENDPOINT = new LinkedHashMap<>();

    private ReportRegistry() {{
    }}

    static {{
{entries or "        // no convertible reports in the source application"}
    }}

    private static void register(ReportDefinition definition) {{
        BY_ENDPOINT.put(definition.endpoint(), definition);
    }}

    /** All reports, in the order they appeared in the Access application. */
    public static List<ReportDefinition> all() {{
        return List.copyOf(BY_ENDPOINT.values());
    }}

    /** Look up a report by its URL slug. */
    public static Optional<ReportDefinition> find(String endpoint) {{
        return Optional.ofNullable(BY_ENDPOINT.get(endpoint));
    }}
{skipped_comment}
}}
"""

    def _registry_entry(self, d: ReportDefinition) -> str:
        columns = ",\n".join(
            f'                        new ReportDefinition.Column("{_q(f.key)}", '
            f'"{_q(f.label)}", "{f.field_type.value}", "{f.align}")'
            for f in d.fields
        )
        groups = ",\n".join(
            f'                        new ReportDefinition.Group("{_q(g.key)}", '
            f'"{_q(g.label)}", "{g.direction}")'
            for g in d.groups
        )
        totals = ",\n".join(
            f'                        new ReportDefinition.Total("{_q(t.key)}", '
            f'"{t.function}", "{_q(t.label)}")'
            for t in d.totals
        )
        params = ",\n".join(
            f'                        new ReportDefinition.Parameter("{_q(p.bind_name)}", '
            f'"{_q(p.access_name)}", "{_JAVA_TYPE_DEFAULTS.get(p.java_type, p.java_type)}", '
            f'{str(p.required).lower()})'
            for p in d.parameters
        )
        notes = ",\n".join(
            f'                        "{_q(n)}"' for n in d.notes
        )

        def block(body: str) -> str:
            return f"List.of(\n{body})" if body else "List.of()"

        return f"""        register(new ReportDefinition(
                "{_q(d.name)}",
                "{_q(d.title)}",
                "{_q(d.endpoint)}",
                \"\"\"
{self._sql_block(d.sql)}\"\"\",
                {block(columns)},
                {block(groups)},
                {block(totals)},
                {block(params)},
                "{d.status.value}",
                {block(notes)}));
"""

    @staticmethod
    def _sql_block(sql: str) -> str:
        """Render SQL inside a Java text block.

        A text block strips incidental indentation, so the SQL is indented
        uniformly and any embedded backslash or `"""` is escaped.
        """
        safe = sql.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        return "".join(f"                {line}\n" for line in safe.splitlines() or [""])

    def _row_class(self) -> str:
        return f"""package {self.package};

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * One row of report output, preserving column order.
 */
public final class ReportRow {{

    private final Map<String, Object> values;

    public ReportRow(Map<String, Object> values) {{
        this.values = new LinkedHashMap<>(values);
    }}

    public Object get(String key) {{
        return values.get(key);
    }}

    /** Column value as display text; {{@code null}} becomes an empty string. */
    public String text(String key) {{
        Object v = values.get(key);
        return v == null ? "" : String.valueOf(v);
    }}

    /** Column value as a number, or {{@code null}} when absent/non-numeric. */
    public java.math.BigDecimal number(String key) {{
        Object v = values.get(key);
        if (v == null) {{
            return null;
        }}
        if (v instanceof java.math.BigDecimal bd) {{
            return bd;
        }}
        if (v instanceof Number n) {{
            return new java.math.BigDecimal(n.toString());
        }}
        try {{
            return new java.math.BigDecimal(String.valueOf(v).trim());
        }} catch (NumberFormatException ex) {{
            return null;
        }}
    }}

    public Map<String, Object> asMap() {{
        return Map.copyOf(values);
    }}
}}
"""

    def _data_class(self) -> str:
        return f"""package {self.package};

import java.util.List;

/**
 * A report's resolved definition together with the rows it returned.
 */
public record ReportData(ReportDefinition definition, List<ReportRow> rows) {{

    public int rowCount() {{
        return rows.size();
    }}

    /** Compute one of the report's declared totals across all rows. */
    public java.math.BigDecimal total(ReportDefinition.Total total) {{
        java.math.BigDecimal sum = java.math.BigDecimal.ZERO;
        java.math.BigDecimal min = null;
        java.math.BigDecimal max = null;
        long count = 0;
        for (ReportRow row : rows) {{
            java.math.BigDecimal v = row.number(total.key());
            if (v == null) {{
                continue;
            }}
            count++;
            sum = sum.add(v);
            min = (min == null || v.compareTo(min) < 0) ? v : min;
            max = (max == null || v.compareTo(max) > 0) ? v : max;
        }}
        return switch (total.function()) {{
            case "COUNT" -> java.math.BigDecimal.valueOf(count);
            case "MIN" -> min == null ? java.math.BigDecimal.ZERO : min;
            case "MAX" -> max == null ? java.math.BigDecimal.ZERO : max;
            case "AVG" -> count == 0
                    ? java.math.BigDecimal.ZERO
                    : sum.divide(java.math.BigDecimal.valueOf(count), 4,
                                 java.math.RoundingMode.HALF_UP);
            default -> sum;
        }};
    }}
}}
"""

    def _service_class(self) -> str:
        return f"""package {self.package};

import java.util.List;
import java.util.Map;

import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Executes converted Access reports.
 *
 * <p>SQL comes from {{@link ReportRegistry}} (generated, fixed at build time)
 * and request values are always bound by name, so no request input can reach
 * the statement text.
 */
@Service
public class ReportService {{

    private final NamedParameterJdbcTemplate jdbc;

    public ReportService(NamedParameterJdbcTemplate jdbc) {{
        this.jdbc = jdbc;
    }}

    /** All registered reports. */
    public List<ReportDefinition> list() {{
        return ReportRegistry.all();
    }}

    /**
     * Run a report.
     *
     * @param endpoint the report's URL slug
     * @param params raw request parameters, resolved against the report's
     *        declared parameter list
     * @throws ReportNotFoundException if no report has that slug
     * @throws IllegalArgumentException if a required parameter is missing or
     *         has the wrong type
     */
    @Transactional(readOnly = true)
    public ReportData run(String endpoint, Map<String, String> params) {{
        ReportDefinition definition = ReportRegistry.find(endpoint)
                .orElseThrow(() -> new ReportNotFoundException(endpoint));

        Map<String, Object> bound = definition.bind(params);
        List<ReportRow> rows = jdbc.query(
                definition.sql(),
                bound,
                (rs, rowNum) -> {{
                    var meta = rs.getMetaData();
                    int columns = meta.getColumnCount();
                    Map<String, Object> values = new java.util.LinkedHashMap<>();
                    for (int i = 1; i <= columns; i++) {{
                        String label = meta.getColumnLabel(i);
                        values.put(label == null ? meta.getColumnName(i) : label,
                                   rs.getObject(i));
                    }}
                    return new ReportRow(values);
                }});

        return new ReportData(definition, rows);
    }}

    /** Thrown when a report slug does not exist. */
    public static class ReportNotFoundException extends RuntimeException {{
        public ReportNotFoundException(String endpoint) {{
            super("No such report: " + endpoint);
        }}
    }}
}}
"""

    def _csv_writer(self) -> str:
        return f"""package {self.package};

import java.io.IOException;
import java.io.Writer;

/**
 * Writes report data as RFC 4180 CSV.
 *
 * <p>Fields containing a comma, quote, CR or LF are quoted, and embedded
 * quotes are doubled. A leading {{@code =}}, {{@code +}}, {{@code -}} or
 * {{@code @}} is prefixed with a single quote so spreadsheet software does not
 * evaluate exported data as a formula.
 */
public final class CsvReportWriter {{

    private CsvReportWriter() {{
    }}

    public static void write(ReportData data, Writer out) throws IOException {{
        ReportDefinition definition = data.definition();
        var keys = definition.columnKeys();

        // Header row uses the report's display labels.
        for (int i = 0; i < definition.columns().size(); i++) {{
            if (i > 0) {{
                out.write(',');
            }}
            out.write(escape(definition.columns().get(i).label()));
        }}
        out.write("\\r\\n");

        for (ReportRow row : data.rows()) {{
            for (int i = 0; i < keys.size(); i++) {{
                if (i > 0) {{
                    out.write(',');
                }}
                out.write(escape(row.text(keys.get(i))));
            }}
            out.write("\\r\\n");
        }}

        // Report-level totals, matching what the PDF renders.
        if (!definition.totals().isEmpty()) {{
            out.write("\\r\\n");
            for (ReportDefinition.Total total : definition.totals()) {{
                out.write(escape(total.function() + " of " + total.label()));
                out.write(',');
                out.write(escape(data.total(total).stripTrailingZeros().toPlainString()));
                out.write("\\r\\n");
            }}
        }}

        out.flush();
    }}

    static String escape(String value) {{
        if (value == null || value.isEmpty()) {{
            return "";
        }}
        String v = value;
        char first = v.charAt(0);
        if (first == '=' || first == '+' || first == '-' || first == '@') {{
            v = "'" + v;
        }}
        boolean mustQuote = v.indexOf(',') >= 0 || v.indexOf('"') >= 0
                || v.indexOf('\\n') >= 0 || v.indexOf('\\r') >= 0;
        if (!mustQuote) {{
            return v;
        }}
        return '"' + v.replace("\\"", "\\"\\"") + '"';
    }}
}}
"""

    def _pdf_writer(self) -> str:
        return f"""package {self.package};

import java.io.OutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

/**
 * Renders report data as a tabular PDF with group breaks and totals.
 *
 * <p>Scope follows spec section 20: a clean modern tabular report, not a
 * pixel reproduction of the Access report layout.
 */
public final class PdfReportWriter {{

    private static final Font TITLE_FONT =
            FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
    private static final Font GROUP_FONT =
            FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);
    private static final Font HEADER_FONT =
            FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9);
    private static final Font BODY_FONT =
            FontFactory.getFont(FontFactory.HELVETICA, 9);
    private static final Font TOTAL_FONT =
            FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9);

    private PdfReportWriter() {{
    }}

    public static void write(ReportData data, OutputStream out) throws DocumentException {{
        ReportDefinition definition = data.definition();
        List<String> keys = definition.columnKeys();

        // Landscape once a report gets wide enough to need it.
        Document document = new Document(
                keys.size() > 6 ? PageSize.A4.rotate() : PageSize.A4,
                36, 36, 42, 42);
        PdfWriter.getInstance(document, out);
        document.open();
        try {{
            Paragraph title = new Paragraph(definition.title(), TITLE_FONT);
            title.setSpacingAfter(10f);
            document.add(title);

            if (data.rows().isEmpty()) {{
                document.add(new Paragraph("No data for the selected criteria.", BODY_FONT));
                return;
            }}

            List<ReportDefinition.Group> groups = definition.groups();
            if (groups.isEmpty()) {{
                document.add(table(definition, data.rows(), keys));
            }} else {{
                writeGrouped(document, data, definition, keys, groups);
            }}

            if (!definition.totals().isEmpty()) {{
                Paragraph spacer = new Paragraph(" ", BODY_FONT);
                document.add(spacer);
                for (ReportDefinition.Total total : definition.totals()) {{
                    document.add(new Paragraph(
                            total.function() + " of " + total.label() + ": "
                                    + format(data.total(total)),
                            TOTAL_FONT));
                }}
            }}
        }} finally {{
            document.close();
        }}
    }}

    /** Emit one table per group value, with a heading and per-group subtotals. */
    private static void writeGrouped(
            Document document,
            ReportData data,
            ReportDefinition definition,
            List<String> keys,
            List<ReportDefinition.Group> groups) throws DocumentException {{

        // Rows arrive pre-sorted by the report's grouping levels, so a single
        // pass is enough to find the breaks.
        ReportDefinition.Group group = groups.get(0);
        List<String> detailKeys = keys.stream()
                .filter(k -> !k.equals(group.key()))
                .toList();

        int start = 0;
        List<ReportRow> rows = data.rows();
        while (start < rows.size()) {{
            String current = rows.get(start).text(group.key());
            int end = start;
            while (end < rows.size() && rows.get(end).text(group.key()).equals(current)) {{
                end++;
            }}
            List<ReportRow> slice = rows.subList(start, end);

            Paragraph heading = new Paragraph(
                    group.label() + ": " + (current.isEmpty() ? "(none)" : current),
                    GROUP_FONT);
            heading.setSpacingBefore(8f);
            heading.setSpacingAfter(4f);
            document.add(heading);

            document.add(table(definition, slice, detailKeys));

            for (ReportDefinition.Total total : definition.totals()) {{
                if (total.key().equals(group.key())) {{
                    continue;
                }}
                ReportData sub = new ReportData(definition, slice);
                Paragraph subtotal = new Paragraph(
                        "    " + total.label() + " subtotal: " + format(sub.total(total)),
                        TOTAL_FONT);
                subtotal.setSpacingAfter(4f);
                document.add(subtotal);
            }}

            start = end;
        }}
    }}

    private static PdfPTable table(
            ReportDefinition definition,
            List<ReportRow> rows,
            List<String> keys) throws DocumentException {{

        PdfPTable table = new PdfPTable(Math.max(keys.size(), 1));
        table.setWidthPercentage(100f);
        table.setHeaderRows(1);

        for (String key : keys) {{
            ReportDefinition.Column column = definition.column(key);
            String label = column == null ? key : column.label();
            PdfPCell cell = new PdfPCell(new Phrase(label, HEADER_FONT));
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setPaddingBottom(4f);
            table.addCell(cell);
        }}

        for (ReportRow row : rows) {{
            for (String key : keys) {{
                ReportDefinition.Column column = definition.column(key);
                boolean numeric = column != null && column.numeric();
                String text = numeric
                        ? formatNullable(row.number(key), row.text(key))
                        : row.text(key);
                PdfPCell cell = new PdfPCell(new Phrase(text, BODY_FONT));
                cell.setHorizontalAlignment(
                        numeric ? Element.ALIGN_RIGHT : Element.ALIGN_LEFT);
                table.addCell(cell);
            }}
        }}
        return table;
    }}

    private static String formatNullable(BigDecimal value, String fallback) {{
        return value == null ? fallback : format(value);
    }}

    private static String format(BigDecimal value) {{
        if (value == null) {{
            return "";
        }}
        return value.setScale(2, RoundingMode.HALF_UP)
                .stripTrailingZeros()
                .toPlainString();
    }}
}}
"""

    def _controller_class(self) -> str:
        pdf_import = ""
        pdf_endpoint = ""
        if self.needs_pdf_dependency:
            pdf_import = "import com.lowagie.text.DocumentException;\n"
            pdf_endpoint = f"""
    /** Render a report as PDF. */
    @GetMapping("/{{endpoint}}/pdf")
    public ResponseEntity<byte[]> pdf(
            @PathVariable String endpoint,
            @RequestParam(required = false) Map<String, String> params) {{

        ReportData data = reportService.run(endpoint, params);
        java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream();
        try {{
            PdfReportWriter.write(data, buffer);
        }} catch (DocumentException ex) {{
            throw new ReportRenderingException("Failed to render PDF for " + endpoint, ex);
        }}

        return ResponseEntity.ok()
                .contentType(MediaType.APPLICATION_PDF)
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        attachment(data.definition().endpoint() + ".pdf"))
                .body(buffer.toByteArray());
    }}
"""

        return f"""package {self.package};

import java.io.IOException;
import java.io.StringWriter;
import java.util.List;
import java.util.Map;

{pdf_import}import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Report endpoints: JSON metadata, JSON data, CSV and PDF exports.
 */
@RestController
@RequestMapping("/api/reports")
public class ReportController {{

    private final ReportService reportService;

    public ReportController(ReportService reportService) {{
        this.reportService = reportService;
    }}

    /** List available reports and the parameters each one needs. */
    @GetMapping
    public List<ReportSummary> list() {{
        return reportService.list().stream()
                .map(d -> new ReportSummary(
                        d.name(),
                        d.title(),
                        d.endpoint(),
                        d.supportStatus(),
                        d.columns(),
                        d.parameters(),
                        d.notes()))
                .toList();
    }}

    /** Run a report and return its rows as JSON. */
    @GetMapping("/{{endpoint}}")
    public ReportResponse json(
            @PathVariable String endpoint,
            @RequestParam(required = false) Map<String, String> params) {{

        ReportData data = reportService.run(endpoint, params);
        return new ReportResponse(
                data.definition().name(),
                data.definition().title(),
                data.definition().columns(),
                data.rows().stream().map(ReportRow::asMap).toList(),
                data.rowCount());
    }}

    /** Export a report as CSV. */
    @GetMapping("/{{endpoint}}/csv")
    public ResponseEntity<String> csv(
            @PathVariable String endpoint,
            @RequestParam(required = false) Map<String, String> params) {{

        ReportData data = reportService.run(endpoint, params);
        StringWriter writer = new StringWriter();
        try {{
            CsvReportWriter.write(data, writer);
        }} catch (IOException ex) {{
            throw new ReportRenderingException("Failed to render CSV for " + endpoint, ex);
        }}

        return ResponseEntity.ok()
                .contentType(new MediaType("text", "csv", java.nio.charset.StandardCharsets.UTF_8))
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        attachment(data.definition().endpoint() + ".csv"))
                .body(writer.toString());
    }}
{pdf_endpoint}
    private static String attachment(String filename) {{
        return "attachment; filename=\\"" + filename.replace("\\"", "") + "\\"";
    }}

    @ExceptionHandler(ReportService.ReportNotFoundException.class)
    public ResponseEntity<Map<String, String>> notFound(
            ReportService.ReportNotFoundException ex) {{
        return ResponseEntity.status(404).body(Map.of("error", ex.getMessage()));
    }}

    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<Map<String, String>> badRequest(IllegalArgumentException ex) {{
        return ResponseEntity.badRequest().body(Map.of("error", ex.getMessage()));
    }}

    /** Report metadata for the frontend's parameter form. */
    public record ReportSummary(
            String name,
            String title,
            String endpoint,
            String supportStatus,
            List<ReportDefinition.Column> columns,
            List<ReportDefinition.Parameter> parameters,
            List<String> notes) {{}}

    /** Report rows plus the column metadata needed to render them. */
    public record ReportResponse(
            String name,
            String title,
            List<ReportDefinition.Column> columns,
            List<Map<String, Object>> rows,
            int rowCount) {{}}

    /** Thrown when a report's bytes could not be produced. */
    public static class ReportRenderingException extends RuntimeException {{
        public ReportRenderingException(String message, Throwable cause) {{
            super(message, cause);
        }}
    }}
}}
"""


def generate_report_sources(
    definitions: Iterable[ReportDefinition],
    *,
    base_package: str = "com.generated.app",
    report_strategy: str = "pdf",
) -> tuple[dict[str, str], bool]:
    """Generate report Java sources.

    Returns ``(files, needs_pdf_dependency)`` where ``files`` maps a bare Java
    file name to its source.
    """
    generator = SpringReportGenerator(
        definitions, base_package=base_package, report_strategy=report_strategy
    )
    return generator.generate(), generator.needs_pdf_dependency
